variable "aws_region" {
  type        = string
  description = "The AWS region to launch the instance in"
  default     = "ap-southeast-2"
}

variable "instance_type" {
  type        = string
  description = "The type of EC2 instance to launch"
  default     = "t3.micro"
}

variable "subnet_id" {
  type        = string
  description = "The ID of the subnet in which to launch the instance"

  validation {
    condition     = length(regexall("^subnet-[\\d|\\w]+$", var.subnet_id)) == 1
    error_message = "The subnet_id variable must match the pattern ^subnet-[\\d|\\w]+$"
  }
}

variable "name_prefix" {
  type        = string
  description = "The prefix to apply to the beginning of names generated by this module"
}

variable "tags" {
  type        = map(string)
  description = "Key/Value pairs to pass to AWS as tags"
  default     = {}
}

variable "instance_count" {
  type        = number
  description = "The number of instances to create"
  default     = 0

  validation {
    condition     = var.instance_count >= 0
    error_message = "The instance_count variable must be greater than or equal to 0"
  }
}
